//! `host.toml` generation — FRM-BO-11..14, ADR-0032, CLNH-10a.
//!
//! The host reads exactly one configuration file at startup, and absent
//! required keys is a startup error (CLNH-13). Nothing in the toolchain wrote
//! that file: `clean-host-core` specifies the reader, `clean.toml` describes a
//! different thing, and Manager is barred from writing to `dist/` (MGR-02).
//! ADR-0032 assigns authorship here, because the framework is the only
//! component holding both inputs the derivation needs — the compiled guest and
//! the target's `host.wit`.
//!
//! # What this module decides, and what it deliberately does not
//!
//! **`[host] deployment-mode` is not generated.** The schema table in
//! `host.toml.md` lists `name`, `version`, and `component-model` as generated
//! and `deployment`/`deployment-mode` as operator-supplied, and FRM-BO-14 puts
//! deployment-time values in `deploy/host.toml`. Emitting one here would mean
//! packaging silently decides how the artifact is deployed — a build-time
//! guess about a runtime fact. Omitting it is also the safe direction:
//! `clean-host-core` defaults an absent key to `production`, so the failure
//! mode of silence is a *stricter* deployment, never a reference backend
//! reaching production unnoticed.
//!
//! **`[bridges]` is derived, not configured** (FRM-BO-12). Today's guests
//! import no `clean:*` capability, so the derived set is empty and the block is
//! omitted rather than written empty — an empty block and an absent one mean
//! the same thing to the reader, and the absent form does not read as a
//! placeholder someone should fill in. When capability imports arrive, this is
//! where the intersection lands.
//!
//! # The path agreement
//!
//! `[guest] wasm` is relative, and `clean-host-core` resolves it **against the
//! directory holding the config file**, not the process CWD. That single fact
//! forces the value, and it differs between the two places this file is
//! written:
//!
//! | Written to | Sits beside | `[guest] wasm` |
//! |---|---|---|
//! | `dist/host.toml` | `dist/app.wasm` | `app.wasm` |
//! | `<archive>/config/host.toml` | `<archive>/app.wasm` | `../app.wasm` |
//!
//! Hence [`Placement`]: the caller states where the file will live, and the
//! generator emits the path that resolves from there. Getting this wrong
//! produces a file that parses cleanly and then fails at startup with a
//! missing-component error, which is why it is a type rather than a comment.

use crate::manifest::Manifest;

/// Where the generated file will be written, which decides how `[guest] wasm`
/// must be spelled.
///
/// Relative paths in `host.toml` resolve against the config file's own
/// directory, so the same guest needs a different path depending on how deep
/// the config sits relative to the component.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum Placement {
    /// `dist/host.toml`, beside `dist/app.wasm`. What `cln run <project>` and
    /// `cln dev` pass through.
    Dist,
    /// `config/host.toml` inside a `.clapp`, one directory below the
    /// `app.wasm` at the archive root (Manager §00.14).
    Archive,
}

impl Placement {
    /// The `[guest] wasm` value that resolves to the component from here.
    fn wasm_path(self) -> &'static str {
        match self {
            Placement::Dist => "app.wasm",
            // Up out of `config/` to the archive root. Manager §00.14 fixes
            // both ends of this: `app.wasm` at the root, `config/host.toml`
            // one level down.
            Placement::Archive => "../app.wasm",
        }
    }
}

/// Generate the `host.toml` body for a project.
///
/// Total, per FRM-BO-11: produced from project state alone, never by reading a
/// previous copy, so a stale or hand-edited file cannot influence a build.
pub fn generate(manifest: &Manifest, placement: Placement) -> String {
    let host = manifest
        .target_section()
        .map(|t| t.host.as_str())
        .unwrap_or("clean-cli");
    let host_version = manifest
        .target_section()
        .map(|t| t.version.as_str())
        .unwrap_or("0.1.0");

    let mut out = String::new();

    // FRM-BO-11: the header names the file as generated and points at the
    // editable path, because the failure it prevents — someone edits `dist/`
    // and loses it on the next build — is silent otherwise.
    out.push_str(
        "# GENERATED by clean-framework at `cln build`. Do not edit.\n\
         #\n\
         # This file is a build output with the same status as `app.wasm`:\n\
         # reproducible from project state, safe to delete, and overwritten on\n\
         # every build. To change it, edit `clean.toml` for build-time values,\n\
         # or `deploy/host.toml` for deployment values — the latter is merged\n\
         # over this file at `cln package` (FRM-BO-14).\n",
    );
    out.push_str(&format!("#\n# Project: {}\n\n", manifest.project.name));

    out.push_str("[host]\n");
    out.push_str(&format!("name            = \"{host}\"\n"));
    out.push_str(&format!("version         = \"{host_version}\"\n"));
    // The component-model level the toolchain targets. WASI 0.3 is the
    // baseline the host schema states.
    out.push_str("component-model = \"0.3.0\"\n");
    // `deployment` and `deployment-mode` are deliberately absent — see the
    // module comment. An absent mode reads as `production` in host-core, so
    // silence here is the strict default rather than a permissive one.
    out.push('\n');

    out.push_str("[guest]\n");
    out.push_str(&format!("name  = \"{}\"\n", manifest.project.name));
    out.push_str(&format!("wasm  = \"{}\"\n", placement.wasm_path()));
    out.push_str(&format!("world = \"{}\"\n", guest_world(manifest)));

    out.push_str(
        "\n\
         # No `[bridges]` block: this guest imports no capability, and FRM-BO-12\n\
         # derives the block from imports rather than from configuration, so\n\
         # there is nothing to write.\n",
    );

    out
}

/// The value for `[guest] world`.
///
/// This is the one place the build target does not answer the question
/// directly. `[build] target = "wasm32-cli"` maps to the world name `cli`
/// (Platform 07 §7.2), but clean-cli declares *two* CLI worlds — `cli`
/// (named-subcommand) and `cli-default` (raw argv) — and CLIH-20 makes them
/// disjoint: a guest exports `commands` or `default`, never both. The target
/// triple cannot express which, because it names a machine target, not a
/// calling convention.
///
/// Until the compiler records the world it emitted in the build manifest, the
/// framework picks `cli-default`. That is the mode clean-cli implements today,
/// and it is what the compiler will emit first. The cost of the guess is
/// bounded and visible: `[guest] world` is metadata, and clean-cli decides the
/// real mode from the guest's exports, warning on stderr if this key disagrees
/// (CLIH-06). So a wrong value here is a warning, never a wrong execution.
fn guest_world(manifest: &Manifest) -> &'static str {
    match manifest.world() {
        Some("cli") => "cli-default",
        Some(other) => match other {
            "server" => "server",
            "browser" => "browser",
            "embedded" => "embedded",
            _ => "cli-default",
        },
        None => "cli-default",
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::manifest::Manifest;

    fn manifest(body: &str) -> Manifest {
        toml::from_str(body).unwrap()
    }

    const CLI: &str = r#"
[project]
name = "hello-world"
version = "0.1.0"

[build]
target = "wasm32-cli"

[target]
host = "clean-cli"
version = "0.1.0"
"#;

    /// The path agreement, stated as a test because a wrong value here parses
    /// fine and only fails at startup.
    #[test]
    fn wasm_path_follows_the_config_files_own_directory() {
        let dist = generate(&manifest(CLI), Placement::Dist);
        assert!(
            dist.contains(r#"wasm  = "app.wasm""#),
            "dist/host.toml sits beside app.wasm:\n{dist}"
        );

        let archive = generate(&manifest(CLI), Placement::Archive);
        assert!(
            archive.contains(r#"wasm  = "../app.wasm""#),
            "config/host.toml is one level below the archive root:\n{archive}"
        );
    }

    /// A packaged artifact must not carry a build-time guess about how it is
    /// deployed. Absent means `production` in host-core, which is the safe end.
    #[test]
    fn deployment_mode_is_never_generated() {
        for placement in [Placement::Dist, Placement::Archive] {
            let out = generate(&manifest(CLI), placement);
            assert!(
                !out.contains("deployment-mode"),
                "generated a deployment-mode key, which is the operator's to \
                 supply (FRM-BO-14):\n{out}"
            );
        }
    }

    /// `wasm32-cli` maps to world `cli`, but the world clean-cli implements is
    /// `cli-default`. Emitting `cli` would make every run warn.
    #[test]
    fn a_cli_target_declares_the_default_handler_world() {
        let out = generate(&manifest(CLI), Placement::Dist);
        assert!(out.contains(r#"world = "cli-default""#), "{out}");
    }

    #[test]
    fn the_generated_file_names_itself_as_generated() {
        let out = generate(&manifest(CLI), Placement::Dist);
        assert!(out.starts_with("# GENERATED"), "{out}");
        assert!(
            out.contains("deploy/host.toml"),
            "the header must name the editable path (FRM-BO-11):\n{out}"
        );
    }

    /// Whatever else changes, the output has to be a config `clean-host-core`
    /// accepts: the three required `[host]` keys and the three `[guest]` ones.
    #[test]
    fn carries_every_key_the_reader_requires() {
        let out = generate(&manifest(CLI), Placement::Dist);
        let parsed: toml::Value = toml::from_str(&out).expect("generated invalid TOML");

        for key in ["name", "version", "component-model"] {
            assert!(parsed["host"].get(key).is_some(), "[host] {key} missing:\n{out}");
        }
        for key in ["name", "wasm", "world"] {
            assert!(parsed["guest"].get(key).is_some(), "[guest] {key} missing:\n{out}");
        }
    }

    /// FRM-BO-12: nothing imports a capability yet, so nothing may be claimed.
    #[test]
    fn no_bridges_are_claimed_for_a_guest_that_imports_none() {
        let out = generate(&manifest(CLI), Placement::Dist);
        let parsed: toml::Value = toml::from_str(&out).unwrap();
        assert!(
            parsed.get("bridges").is_none(),
            "a guest with no capability imports must produce no [bridges]:\n{out}"
        );
    }

    /// Generation is a pure function of project state (FRM-BO-11), which is
    /// what keeps packaging byte-reproducible.
    #[test]
    fn generation_is_deterministic() {
        let a = generate(&manifest(CLI), Placement::Archive);
        let b = generate(&manifest(CLI), Placement::Archive);
        assert_eq!(a, b);
    }
}
