#!/usr/bin/env python3
"""Generate hello-cli.wat — a real `cli-default` guest for the framework's suite.

This stands in for what the Clean compiler will emit once it can target
`cli-default`. It exists so the framework's own tests can prove the artifact it
produces is one a host will actually run, rather than one that merely packages
and hashes cleanly.

**Why this is authored at the component level.** The earlier fixture was a core
module fed through `wasm-tools component embed` + `component new`. That path
cannot express this contract. WASI 0.3 replaced Preview 2's byte-oriented
`write` with a native `stream<u8>`, so writing to stdout means creating a
stream with `stream.new`, handing its readable end to `write-via-stream`, and
pushing bytes into the writable end — canonical built-ins that exist only at
the component level. A core module has no way to name them, so there is nothing
for `embed` to bind.

**Why two core modules.** `stream.write` takes a `memory` option, and the
memory it needs lives in the module that wants to call it — a cycle. Splitting
memory into its own module breaks it: memory is instantiated first, the
built-ins are declared against it, and the main module is instantiated with
both already in hand.

Derived from `clean-cli/testing/hello/gen.py`, which is the reference guest for
this contract and the source of truth for its shape. Kept as a sibling copy
rather than shared, because the framework's test suite must not depend on
another repository being checked out beside it.
"""
import pathlib

HERE = pathlib.Path(__file__).parent

# What the guest prints. CLIH-10 makes this byte-exact: exactly these bytes on
# stdout and nothing else, which is what the end-to-end test asserts on.
MESSAGE = "hello\n"

# Linear memory layout. Fixed addresses because nothing here is allocated at
# runtime: the message is static data, and the call needs one scratch slot.
MSG_ADDR = 100
HEAP = 2048

message_bytes = MESSAGE.encode("utf-8")


def wat_string(raw):
    """Render bytes as a WAT string literal.

    WAT wants double quotes and its own escapes; Python's `repr` produces
    single quotes for this input, which the parser rejects. Every byte outside
    printable ASCII becomes a `\\hh` escape so the literal stays valid whatever
    the message becomes.
    """
    out = []
    for b in raw:
        if b == 0x22:      # "
            out.append('\\"')
        elif b == 0x5C:    # backslash
            out.append("\\\\")
        elif 0x20 <= b < 0x7F:
            out.append(chr(b))
        else:
            out.append(f"\\{b:02x}")
    return '"' + "".join(out) + '"'


MESSAGE_LITERAL = wat_string(message_bytes)

WAT = f"""\
;; hello-cli — a real `cli-default` guest, standing in for compiler output.
;;
;; GENERATED by gen.py. Do not edit hello-cli.wat directly.
;;
;; Exports `run(argv: list<string>, stdin-tty: bool) -> u8` per clean-cli's
;; host.wit, writes {MESSAGE!r} to stdout through wasi:cli/stdout@0.3.0, and
;; returns 0.

(component
  ;; wasi:cli/types carries `error-code`, which stdout's result refers to. It is
  ;; imported separately so the stdout instance can alias the same type rather
  ;; than declaring a structurally-equal copy — the component model compares
  ;; these nominally, and a second declaration is a different type.
  (import "wasi:cli/types@0.3.0" (instance $ty
    (type $ec0 (enum "io" "illegal-byte-sequence" "pipe"))
    (export "error-code" (type (eq $ec0)))
  ))
  (alias export $ty "error-code" (type $ecx))

  (import "wasi:cli/stdout@0.3.0" (instance $so
    (alias outer 1 $ecx (type $ec))
    (export "error-code" (type (eq $ec)))
    (type $s (stream u8))
    (type $r (result (error $ec)))
    (type $f (future $r))
    (type $wf (func (param "data" $s) (result $f)))
    (export "write-via-stream" (func (type $wf)))
  ))

  ;; Stage 1 — memory alone, so `stream.write` (which requires a memory option)
  ;; can be declared before the module that calls it is instantiated.
  (core module $mem_m
    (memory (export "memory") 1)
    ;; Nothing host-allocated outlives this call, so a fixed bump above the
    ;; static data satisfies the ABI.
    (func (export "realloc") (param i32 i32 i32 i32) (result i32)
      (i32.const {HEAP}))
  )
  (core instance $memi (instantiate $mem_m))
  (alias core export $memi "memory" (core memory $mem))
  (alias core export $memi "realloc" (core func $ral))

  (type $st (stream u8))
  (core func $snew (canon stream.new $st))
  (core func $swrite (canon stream.write $st async (memory $mem)))
  (core func $sdrop (canon stream.drop-writable $st))
  (alias export $so "write-via-stream" (func $wvs))
  ;; Lowered synchronously: `run` is a sync export, and an async lowering would
  ;; require an async lift to match.
  (core func $wvsl (canon lower (func $wvs) (memory $mem)))

  (core module $m
    (import "m" "memory" (memory 1))
    ;; stream.new returns both ends packed into an i64: readable in the low
    ;; 32 bits, writable in the high 32.
    (import "c" "new" (func $new (result i64)))
    (import "c" "write" (func $write (param i32 i32 i32) (result i32)))
    (import "c" "dropw" (func $dropw (param i32)))
    (import "c" "wvs" (func $wvs (param i32) (result i32)))

    (data (i32.const {MSG_ADDR}) {MESSAGE_LITERAL})

    (func (export "run") (param $argv_ptr i32) (param $argv_len i32)
                         (param $stdin_tty i32) (result i32)
      (local $pair i64)
      (local $readable i32)
      (local $writable i32)

      (local.set $pair (call $new))
      (local.set $readable (i32.wrap_i64 (local.get $pair)))
      (local.set $writable
        (i32.wrap_i64 (i64.shr_u (local.get $pair) (i64.const 32))))

      ;; Hand the readable end to stdout before writing, so the bytes have
      ;; somewhere to go. The returned future is dropped: this guest does not
      ;; wait on the flush, and the host's stdout is unbuffered.
      (drop (call $wvs (local.get $readable)))

      (drop (call $write
        (local.get $writable)
        (i32.const {MSG_ADDR})
        (i32.const {len(message_bytes)})))

      ;; Closing the writable end signals end-of-stream, which is what tells
      ;; stdout the write is complete.
      (call $dropw (local.get $writable))

      ;; CLIH-11: 0 is success by convention.
      (i32.const 0))
  )

  (core instance $ci
    (export "new"   (func $snew))
    (export "write" (func $swrite))
    (export "dropw" (func $sdrop))
    (export "wvs"   (func $wvsl))
  )
  (core instance $mi (instantiate $m
    (with "c" (instance $ci))
    (with "m" (instance $memi))
  ))
  (alias core export $mi "run" (core func $run))

  (type $rt (func (param "argv" (list string)) (param "stdin-tty" bool) (result u8)))
  (func $runl (type $rt)
    (canon lift (core func $run) (memory $mem) (realloc $ral) string-encoding=utf8))
  (export "run" (func $runl))
)
"""

(HERE / "hello-cli.wat").write_text(WAT)
print(f"wrote hello-cli.wat ({len(message_bytes)} bytes of output)")
